from functions.get_files_info import get_files_info, schema_get_files_info
from functions.get_file_content import get_file_content, schema_get_file_content
from functions.write_file import schema_write_file
from functions.run_python_file import schema_run_python_file


#available functions to use in the chatbot
available_functions_to_use = [schema_get_files_info,schema_get_file_content,schema_run_python_file,schema_write_file]